# Generated by Django 5.2.7 on 2026-01-22 12:00

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mt5Terminal",
            fields=[
                ("terminal_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="online", max_length=16)),
                ("meta", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pair_id", models.CharField(max_length=64)),
                ("side", models.CharField(choices=[("BUY", "BUY"), ("SELL", "SELL")], max_length=16)),
                ("symbol_a", models.CharField(max_length=32)),
                ("symbol_b", models.CharField(blank=True, max_length=32, null=True)),
                ("qty_a", models.DecimalField(decimal_places=6, max_digits=18)),
                ("qty_b", models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ("order_type", models.CharField(choices=[("MARKET", "MARKET"), ("LIMIT", "LIMIT")], default="MARKET", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("CLAIMED", "CLAIMED"),
                            ("SENT", "SENT"),
                            ("FILLED", "FILLED"),
                            ("REJECTED", "REJECTED"),
                            ("CANCELLED", "CANCELLED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("client_order_id", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="bridge.mt5terminal",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["terminal", "status", "created_at"], name="bridge_orde_terminal_b2fe8c_idx"),
                    models.Index(fields=["pair_id"], name="bridge_orde_pair_id_2e53e4_idx"),
                    models.Index(fields=["claimed_at"], name="bridge_orde_claimed_94dd71_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(choices=[("ACK", "ACK"), ("FILL", "FILL"), ("ERROR", "ERROR"), ("INFO", "INFO")], max_length=32)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="bridge.orderrequest",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="orderrequest",
            constraint=models.UniqueConstraint(fields=("terminal", "client_order_id"), name="uniq_terminal_client_order"),
        ),
    ]
