# Generated by Codex on 2026-01-28

from django.db import migrations


RPC_SQL = """
create or replace function public.bridge_claim_next_order(p_terminal_id text)
returns setof public.bridge_orderrequest
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidate as (
    select id
    from public.bridge_orderrequest
    where status = 'QUEUED'
      and public.bridge_orderrequest.terminal_id = public.bridge_claim_next_order.p_terminal_id
    order by created_at asc
    for update skip locked
    limit 1
  )
  update public.bridge_orderrequest
  set status = 'CLAIMED',
      claimed_at = now()
  from candidate
  where public.bridge_orderrequest.id = candidate.id
  returning public.bridge_orderrequest.*;
end;
$$;
"""


DROP_RPC_SQL = """
drop function if exists public.bridge_claim_next_order(text);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(RPC_SQL, reverse_sql=DROP_RPC_SQL),
    ]
