# Generated by Django 5.2.7 on 2026-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0002_quotedaily_is_provisional'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedaily',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotedaily',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotedaily',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
