# Generated by Django 5.2.7 on 2025-12-29 21:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationMT5Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.CharField(choices=[('A', 'Perna A'), ('B', 'Perna B')], max_length=1)),
                ('symbol', models.CharField(max_length=32)),
                ('ticket', models.BigIntegerField()),
                ('side', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=4)),
                ('volume', models.FloatField()),
                ('price_open', models.FloatField()),
                ('sl', models.FloatField(blank=True, null=True)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=64)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_trades', to='operacoes.operation')),
            ],
            options={
                'unique_together': {('operation', 'leg')},
            },
        ),
    ]
