# Generated by Django 5.2.7 on 2025-12-31 18:26

import django.db.models.deletion
from django.db import migrations, models


def _set_initial_statuses(apps, schema_editor):
    OperationMT5Trade = apps.get_model("operacoes", "OperationMT5Trade")
    OperationMT5Trade.objects.filter(status="").update(status="aberto")


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0003_mt5auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmt5trade',
            name='close_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='operationmt5trade',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationmt5trade',
            name='position_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationmt5trade',
            name='status',
            field=models.CharField(default='aberto', max_length=32),
        ),
        migrations.RunPython(
            _set_initial_statuses,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='MT5IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('RESET_DEMO_DETECTED', 'Reset demo detectado')], default='RESET_DEMO_DETECTED', max_length=64)),
                ('ticket', models.BigIntegerField(blank=True, null=True)),
                ('position_id', models.BigIntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('account_login', models.CharField(blank=True, default='', max_length=32)),
                ('account_server', models.CharField(blank=True, default='', max_length=128)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('equity', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(blank=True, null=True)),
                ('margin_free', models.FloatField(blank=True, null=True)),
                ('margin_mode', models.IntegerField(blank=True, null=True)),
                ('positions_total', models.PositiveIntegerField(default=0)),
                ('from_dt', models.DateTimeField()),
                ('to_dt', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, default='', max_length=32)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mt5_incidents', to='operacoes.operation')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_events', to='operacoes.operationmt5trade')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
