# Generated by Codex on 2026-01-19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operacoes", "0006_operationmt5trade_expiration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="mt5_ticket",
        ),
        migrations.DeleteModel(
            name="MT5AuditEvent",
        ),
        migrations.DeleteModel(
            name="MT5IncidentEvent",
        ),
        migrations.DeleteModel(
            name="OperationMT5Trade",
        ),
    ]
